# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{squall}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Mazzi"]
  s.date = %q{2010-11-17}
  s.description = %q{A Ruby library for working with the OnApp REST API}
  s.email = %q{jmazzi@site5.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/squall.rb",
    "lib/squall/client.rb",
    "lib/squall/hypervisor.rb",
    "lib/squall/virtual_machine.rb",
    "squall.gemspec",
    "test/fixtures/virtual_machines.json",
    "test/fixtures/virtual_machines_1.json",
    "test/helper.rb",
    "test/test_client.rb",
    "test/test_squall.rb",
    "test/test_virtual_machine.rb"
  ]
  s.homepage = %q{http://www.site5.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby library for working with the OnApp REST API}
  s.test_files = [
    "test/helper.rb",
    "test/test_client.rb",
    "test/test_squall.rb",
    "test/test_virtual_machine.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_development_dependency(%q<redgreen>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<redgreen>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<redgreen>, [">= 0"])
  end
end

