--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://<USER>:<PASS>@<URL>:80/virtual_machines/404/build.json?virtual_machine%5Btemplate_id%5D=1
    body: 
    headers: 
      content-type: 
      - application/json
      authorization: 
      - Basic <REDACTED>
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 404
      message: Not Found
    headers: 
      x-ua-compatible: 
      - IE=Edge,chrome=1
      x-powered-by: 
      - Phusion Passenger (mod_rails/mod_rack) 3.0.1
      content-type: 
      - application/json; charset=utf-8
      date: 
      - Wed, 20 Apr 2011 15:54:19 GMT
      server: 
      - Apache/2.2.3 (CentOS)
      x-runtime: 
      - "2.751480"
      set-cookie: 
      - <REDACTED>
      cache-control: 
      - no-cache
      status: 
      - "404"
      transfer-encoding: 
      - chunked
    body: "{\"error\":\"Resource not found\"}"
    http_version: "1.1"
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://<USER>:<PASS>@<URL>:80/virtual_machines/72/build.json?virtual_machine%5Btemplate_id%5D=1
    body: 
    headers: 
      content-type: 
      - application/json
      authorization: 
      - Basic <REDACTED>
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 201
      message: Created
    headers: 
      x-ua-compatible: 
      - IE=Edge,chrome=1
      location: 
      - https://www.example.com/virtual_machines/72
      x-powered-by: 
      - Phusion Passenger (mod_rails/mod_rack) 3.0.1
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "0.163372"
      server: 
      - Apache/2.2.3 (CentOS)
      date: 
      - Wed, 20 Apr 2011 16:02:18 GMT
      set-cookie: 
      - <REDACTED>
      status: 
      - "201"
      cache-control: 
      - no-cache
      transfer-encoding: 
      - chunked
    body: "{\"virtual_machine\":{\"label\":\"Testingagain\",\"cpus\":1,\"operating_system_distro\":\"rhel\",\"created_at\":\"2011-04-20T16:01:10Z\",\"template_id\":1,\"operating_system\":\"linux\",\"cpu_shares\":1,\"updated_at\":\"2011-04-20T16:02:18Z\",\"memory\":256,\"local_remote_access_port\":5901,\"allowed_swap\":true,\"recovery_mode\":false,\"allow_resize_without_reboot\":true,\"xen_id\":null,\"id\":72,\"hypervisor_id\":6,\"user_id\":4,\"template_label\":\"CentOS 5.5 x64\",\"hostname\":\"testingagain.com\",\"booted\":false,\"remote_access_password\":\"sadf234\",\"min_disk_size\":5,\"initial_root_password\":\"213fsdfsd\",\"identifier\":\"asdfdsfsdf\",\"locked\":true,\"built\":false}}"
    http_version: "1.1"