--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :post
    uri: http://user:pass@www.example.com:80/virtual_machines/404/build.json?virtual_machine[template_id]=1
    body: 
    headers: 
      content-type: 
      - application/json
      authorization: 
      - Basic WHAT
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 404
      message: Not Found
    headers: 
      x-ua-compatible: 
      - IE=Edge,chrome=1
      x-powered-by: 
      - Phusion Passenger (mod_rails/mod_rack) 3.0.1
      content-type: 
      - application/json; charset=utf-8
      x-runtime: 
      - "0.052989"
      server: 
      - Apache/2.2.3 (CentOS)
      date: 
      - Mon, 06 Feb 2012 23:18:27 GMT
      set-cookie: 
      - _session_id=fce6d6726d82b2d1a6f0334d6ed7f915; path=/; HttpOnly
      status: 
      - "404"
      cache-control: 
      - no-cache
      transfer-encoding: 
      - chunked
    body: "{\"errors\":[\"Resource not found\"]}"
    http_version: "1.1"
